apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlsql-server
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlsql-server
  template:
    metadata:
      labels:
        app: nlsql-server
    spec:
      containers:
      - name: nlsql-server
        image: jonemark226/nlsql-server:03
        ports:
        - containerPort: 3002
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nlsql-server-service
  namespace: backend
spec:
  selector:
    app: nlsql-server
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
    nodePort: 32002  # Exposing backend via NodePort
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlsql-client
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlsql-client
  template:
    metadata:
      labels:
        app: nlsql-client
    spec:
      containers:
      - name: nlsql-client
        image: jonemark226/nlsql-client:03
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://54.208.243.56:32002/generate"  # Correct backend URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nlsql-client-service
  namespace: frontend
spec:
  selector:
    app: nlsql-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32080  # Exposing frontend via NodePort
  type: NodePort
